# Generated by Django 5.2.6 on 2026-05-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_price_id', models.CharField(blank=True, help_text='ID del Price en Stripe (price_XXXX). Requerido para Checkout.', max_length=200, null=True)),
                ('max_galpones', models.IntegerField(blank=True, help_text='Límite de galpones. Null = ilimitado.', null=True)),
                ('max_usuarios', models.IntegerField(default=5, help_text='Límite de usuarios por empresa.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan',
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email_contacto', models.EmailField(max_length=255, unique=True)),
                ('estado', models.CharField(choices=[('trial', 'Trial'), ('activa', 'Activa'), ('suspendida', 'Suspendida')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='empresas.plan')),
            ],
            options={
                'db_table': 'empresa',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('past_due', 'Pago vencido'), ('canceled', 'Cancelada'), ('trialing', 'En prueba'), ('incomplete', 'Incompleta')], default='active', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_proximo_cobro', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='empresas.empresa')),
            ],
            options={
                'db_table': 'suscripcion',
            },
        ),
    ]
