# Generated by Django 5.2.6 on 2026-05-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo',
                 models.CharField(choices=[('Alimento',
                                            'Alimento'),
                                           ('Medicamento',
                                            'Medicamento'),
                                           ('Vacuna',
                                            'Vacuna')],
                                  max_length=20)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('stock_actual', models.DecimalField(
                    decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(
                    decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[
                 ('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('insumo',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='movimientos',
                                   to='insumos.insumo')),
                ('proveedor',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='movimientos',
                                   to='insumos.proveedor')),
            ],
            options={
                'db_table': 'movimientos_almacen',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
