# Generated by Django 5.2.6 on 2026-05-09 06:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_controlsanitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoalmacen',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlsanitario',
            name='fecha_registro',
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='fecha_hora',
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
