# Generated by Django 5.2.6 on 2026-05-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('insumos', '0003_movimientoalmacen_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsanitario',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controles_sanitarios', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='movimientoalmacen',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_almacen', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='empresas.empresa'),
        ),
    ]
