# Generated by Django 5.2.6 on 2026-06-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_controlsanitario_enfermedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsanitario',
            name='dosis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='controlsanitario',
            name='fecha_aplicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='controlsanitario',
            name='unidad_dosis',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
