# Generated by Django 5.2.6 on 2026-06-15 01:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('lotes', '0004_curvacrecimientoestandar_controlcalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.empresa')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='VentaLote',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_total_vendido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_venta', models.CharField(default='Por unidad', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='ventas.cliente')),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_lotes', to='empresas.empresa')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='lotes.lote')),
            ],
            options={
                'db_table': 'venta_lote',
                'ordering': ['-fecha_venta', '-id_venta'],
            },
        ),
    ]
