# Generated by Django 5.2.6 on 2026-05-07 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galpones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturaGalpon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(max_length=20)),
                ('fuente', models.CharField(default='SIMULADO', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('galpon', models.ForeignKey(db_column='galpon_id', on_delete=django.db.models.deletion.CASCADE, related_name='temperaturas', to='galpones.galpon')),
            ],
            options={
                'db_table': 'temperatura_galpon',
                'ordering': ['-fecha_hora', '-id'],
            },
        ),
    ]
