# Generated by Django 5.2.6 on 2026-05-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatura', '0001_initial'),
        ('usuarios', '0005_usuario_roles_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturagalpon',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperaturas_registradas', to='usuarios.usuario'),
        ),
    ]
