# Generated by Django 5.2.6 on 2026-05-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('temperatura', '0002_add_usuario_to_temperatura_galpon'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturagalpon',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperaturas', to='empresas.empresa'),
        ),
    ]
