# Generated by Django 5.2.6 on 2026-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galpones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galpon',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='galpon',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='galpon',
            name='ubicacion_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
