# Generated by Django 5.2.6 on 2026-05-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galpones', '0002_add_coordenadas_galpon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galpon',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='galpon',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
