# Generated by Django 5.2.6 on 2026-05-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galpones', '0003_fix_coordenadas_max_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galpon',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='galpon',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
