# Generated by Django 5.2.6 on 2026-05-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galpones', '0002_galpon_empresa'),
        ('galpones', '0004_fix_coordenadas_6decimales'),
    ]

    operations = [
    ]
