# Generated by Django 5.2.6 on 2026-06-02 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('insumos', '0005_controlsanitario_enfermedad'),
        ('lotes', '0004_curvacrecimientoestandar_controlcalidad'),
        ('usuarios', '0006_usuario_empresa_usuario_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('Afectacion', 'Afectación por enfermedad'), ('Mortandad', 'Incremento de mortandad')], max_length=30)),
                ('nivel', models.CharField(choices=[('Medio', 'Medio'), ('Alto', 'Alto'), ('Critico', 'Crítico')], default='Alto', max_length=20)),
                ('causa', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('porcentaje_detectado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cantidad_detectada', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida'), ('Resuelta', 'Resuelta')], default='Pendiente', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sanitarias', to='empresas.empresa')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sanitarias', to='lotes.lote')),
                ('registro_enfermedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_sanitarias', to='insumos.controlsanitario')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_sanitarias', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'alerta_sanitaria',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
