# Generated by Django 5.2.6 on 2026-05-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0001_initial'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentacion',
            name='insumo',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='alimentaciones',
                to='insumos.insumo'),
        ),
    ]
