# Generated by Django 5.2.6 on 2026-05-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentacion', '0002_alimentacion_insumo'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentacion',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to='empresas.empresa'),
        ),
    ]
