# Generated by Django 5.2.6 on 2026-05-09 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0002_alimentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMortalidad',
            fields=[
                ('id_muerte', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('causa', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, related_name='registros_mortalidad', to='lotes.lote')),
            ],
            options={
                'db_table': 'registro_mortalidad',
            },
        ),
    ]
