# Generated by Django 5.2.6 on 2026-06-19 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('lotes', '0004_curvacrecimientoestandar_controlcalidad'),
        ('mortandad', '0002_registromortalidad_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionMortalidad',
            fields=[
                ('id_prediccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('riesgo_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel_riesgo', models.CharField(max_length=20)),
                ('temperatura_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('desviacion_alimento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bajas_recientes', models.IntegerField(default=0)),
                ('alerta_sanitaria', models.BooleanField(default=False)),
                ('factores_clave', models.JSONField(blank=True, default=list)),
                ('recomendaciones', models.JSONField(blank=True, default=list)),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_mortalidad', to='empresas.empresa')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_mortalidad', to='lotes.lote')),
            ],
            options={
                'db_table': 'prediccion_mortalidad',
                'ordering': ['-fecha_hora', '-id_prediccion'],
            },
        ),
    ]
