# Generated by Django 5.2.6 on 2026-06-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortandad', '0003_prediccionmortalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionmortalidad',
            name='edad_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediccionmortalidad',
            name='humedad_promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
