export const styles = {
  page: {
    minHeight: '100vh',
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'Poppins', sans-serif",
    padding: '20px',
    position: 'relative',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  pageBg: {
    position: 'fixed',
    inset: 0,
    backgroundImage: 'url(/fondo.png)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    filter: 'blur(7px) brightness(0.8)',
    transform: 'scale(1.08)',
    zIndex: 0,
  },
  card: {
    width: '100%',
    maxWidth: '420px',
    borderRadius: '28px',
    overflow: 'hidden',
    boxShadow: '0 40px 100px rgba(0,0,0,0.35)',
    position: 'relative',
    zIndex: 1,
    animation: 'slideUp 0.5s ease-out',
  },
  topPanel: {
    background: 'linear-gradient(135deg, #E67E22 0%, #D35400 100%)',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 40px 40px',
    minHeight: '220px',
  },
  topOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(0,0,0,0.12)',
  },
  topContent: {
    position: 'relative',
    zIndex: 1,
    textAlign: 'center',
    color: 'white',
  },
  logoWrapper: {
    width: '140px',
    height: '140px',
    borderRadius: '50%',
    overflow: 'hidden',
    border: '3px solid rgba(255,255,255,0.6)',
    margin: '0 auto 16px',
    boxShadow: '0 0 30px rgba(230,126,34,0.4)',
  },
  logo: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  brandTitle: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#ffffff',
    margin: '0 0 6px',
    letterSpacing: '-0.5px',
    textShadow: '0 2px 8px rgba(0,0,0,0.15)',
  },
  brandSubtitle: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.8)',
    letterSpacing: '2.5px',
    textTransform: 'uppercase',
    margin: 0,
  },
  bottomPanel: {
    background: '#ffffff',
    padding: '36px 36px 32px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  welcomeText: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#1c1c1c',
    margin: '0 0 4px',
  },
  welcomeSub: {
    fontSize: '13px',
    color: '#9ca3af',
    margin: '0 0 24px',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
  },
  inputGroup: {
    display: 'flex',
    alignItems: 'center',
    background: '#f9fafb',
    border: '1.5px solid #e5e7eb',
    borderRadius: '12px',
    padding: '0 16px',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  },
  inputGroupFocus: {
    borderColor: '#E67E22',
    boxShadow: '0 0 0 3px rgba(230,126,34,0.1)',
  },
  inputIcon: {
    marginRight: '10px',
    flexShrink: 0,
    color: '#9ca3af',
  },
  input: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    padding: '14px 0',
    fontSize: '14px',
    color: '#111827',
    outline: 'none',
    fontFamily: "'Poppins', sans-serif",
    minWidth: 0,
  },
  togglePassBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex',
    color: '#9ca3af',
  },
  forgotPass: {
    background: 'none',
    border: 'none',
    color: '#E67E22',
    fontSize: '12px',
    fontWeight: '500',
    cursor: 'pointer',
    padding: '0',
    textAlign: 'right',
    fontFamily: "'Poppins', sans-serif",
    alignSelf: 'flex-end',
    marginTop: '-4px',
  },
  error: {
    color: '#dc2626',
    background: '#fee2e2',
    borderRadius: '10px',
    padding: '10px 14px',
    fontSize: '12px',
    margin: '0',
    width: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  button: {
    background: 'linear-gradient(135deg, #E67E22 0%, #D35400 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '14px',
    padding: '15px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 6px 24px rgba(230,126,34,0.4)',
    marginTop: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    fontFamily: "'Poppins', sans-serif",
    transition: 'transform 0.15s, box-shadow 0.15s',
  },
  buttonLoading: {
    background: '#d1d5db',
    boxShadow: 'none',
    cursor: 'not-allowed',
  },
  registerBtn: {
    background: 'transparent',
    border: '1.5px solid #e5e7eb',
    borderRadius: '12px',
    padding: '12px',
    fontSize: '13px',
    fontWeight: '500',
    color: '#6b7280',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    fontFamily: "'Poppins', sans-serif",
    marginTop: '4px',
    transition: 'border-color 0.2s, color 0.2s',
  },
  footer: {
    marginTop: '22px',
    fontSize: '11px',
    color: '#9ca3af',
  },
  spinner: {
    width: '18px',
    height: '18px',
    border: '2px solid rgba(255,255,255,0.3)',
    borderTopColor: 'white',
    borderRadius: '50%',
    animation: 'spin 0.6s linear infinite',
    marginRight: '8px',
  },
}