export const styles = {
  page: {
    minHeight: '100vh',
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'Poppins', sans-serif",
    padding: '20px',
    position: 'relative',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  pageBg: {
    position: 'fixed',
    inset: 0,
    backgroundImage: 'url(/fondo.png)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    filter: 'blur(7px) brightness(0.8)',
    transform: 'scale(1.08)',
    zIndex: 0,
  },
  card: {
    width: '100%',
    maxWidth: '420px',
    borderRadius: '28px',
    overflow: 'hidden',
    boxShadow: '0 40px 100px rgba(0,0,0,0.35)',
    position: 'relative',
    zIndex: 1,
  },
  topPanel: {
    backgroundImage: 'url(/fondo.png)',
    backgroundSize: 'cover',
    backgroundPosition: 'center top',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 40px 40px',
    minHeight: '220px',
  },
  topOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(160deg, rgba(120,53,15,0.7) 0%, rgba(180,83,9,0.75) 100%)',
  },
  topContent: {
    position: 'relative',
    zIndex: 1,
    textAlign: 'center',
    color: 'white',
  },
  logoWrapper: {
    width: '160px',
    height: '160px',
    borderRadius: '50%',
    overflow: 'hidden',
    border: '3px solid #fbbf24',
    margin: '0 auto 16px',
    boxShadow: '0 0 30px rgba(245,158,11,0.5)',
  },
  logo: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  brandTitle: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#fef3c7',
    margin: '0 0 6px',
    letterSpacing: '-0.5px',
  },
  brandSubtitle: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.8)',
    letterSpacing: '2.5px',
    textTransform: 'uppercase',
    margin: 0,
  },
  bottomPanel: {
    background: '#ffffff',
    padding: '40px 36px 36px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  welcomeText: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#1c1c1c',
    margin: '0 0 4px',
  },
  welcomeSub: {
    fontSize: '12px',
    color: '#9ca3af',
    margin: '0 0 28px',
    textAlign: 'center',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    width: '100%',
  },
  inputGroup: {
    display: 'flex',
    alignItems: 'center',
    background: '#f9fafb',
    border: '1.5px solid #e5e7eb',
    borderRadius: '12px',
    padding: '0 16px',
  },
  inputIcon: {
    marginRight: '10px',
    flexShrink: 0,
  },
  input: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    padding: '14px 0',
    fontSize: '14px',
    color: '#111827',
    outline: 'none',
    fontFamily: "'Poppins', sans-serif",
    minWidth: 0,
  },
  error: {
    color: '#dc2626',
    background: '#fee2e2',
    borderRadius: '10px',
    padding: '10px 14px',
    fontSize: '12px',
    margin: '0',
    width: '100%',
    boxSizing: 'border-box',
  },
  button: {
    background: 'linear-gradient(135deg, #f59e0b, #d97706)',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    padding: '15px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    boxShadow: '0 6px 20px rgba(245,158,11,0.4)',
    marginTop: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    fontFamily: "'Poppins', sans-serif",
  },
  buttonLoading: {
    background: '#d1d5db',
    boxShadow: 'none',
    cursor: 'not-allowed',
  },
  footer: {
    marginTop: '24px',
    fontSize: '11px',
    color: '#9ca3af',
  },
}