# Generated by Django 5.2.6 on 2026-05-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_automatica', models.TimeField(blank=True, help_text='Hora diaria en la que se ejecutará el respaldo automático (HH:MM).', null=True)),
                ('activo', models.BooleanField(default=False, help_text='Si es True, el planificador ejecutará el respaldo a la hora configurada.')),
            ],
            options={
                'verbose_name': 'Configuración de Respaldo',
                'verbose_name_plural': 'Configuración de Respaldo',
                'db_table': 'backup_config',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo .json.gz generado.', max_length=255)),
                ('ruta_archivo', models.CharField(help_text='Ruta absoluta en el servidor para localizar el archivo.', max_length=512)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tamano', models.CharField(help_text="Tamaño legible por humanos, ej: '2.4 MB'.", max_length=30)),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='MANUAL', max_length=10)),
            ],
            options={
                'verbose_name': 'Registro de Respaldo',
                'verbose_name_plural': 'Historial de Respaldos',
                'db_table': 'backup_log',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
