# Generated by Django 5.2.6 on 2026-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfig',
            name='mantenimiento_hasta',
            field=models.DateTimeField(blank=True, help_text='Timestamp de auto-desactivación del modo mantenimiento.', null=True),
        ),
        migrations.AddField(
            model_name='backupconfig',
            name='modo_mantenimiento',
            field=models.BooleanField(default=False, help_text='Si True, el sistema bloquea todas las peticiones de no-SuperAdmin.'),
        ),
    ]
