# Generated by Django 5.2.6 on 2026-05-31 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('lotes', '0003_lote_empresa'),
        ('usuarios', '0006_usuario_empresa_usuario_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvaCrecimientoEstandar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=100)),
                ('edad_dias', models.IntegerField()),
                ('peso_estandar', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'curva_crecimiento_estandar',
            },
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('peso_registrado', models.DecimalField(decimal_places=4, max_digits=10)),
                ('edad_dias', models.IntegerField()),
                ('peso_estandar', models.DecimalField(decimal_places=4, max_digits=10)),
                ('porcentaje_diferencia', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estado_desarrollo', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, related_name='controles_calidad', to='empresas.empresa')),
                ('id_lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.CASCADE, related_name='controles_calidad', to='lotes.lote')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'control_calidad',
            },
        ),
    ]
