# Generated by Django 5.2.6 on 2026-04-11 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
        ('usuarios', '0005_usuario_roles_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacoraevento',
            options={'ordering': ['-fecha_hora', '-id']},
        ),
        migrations.RenameField(
            model_name='bitacoraevento',
            old_name='detalle',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='bitacoraevento',
            old_name='created_at',
            new_name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='entidad_id',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='nom_usuario',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='path',
        ),
        migrations.RemoveField(
            model_name='bitacoraevento',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='bitacoraevento',
            name='accion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bitacoraevento',
            name='usuario',
            field=models.ForeignKey(
                blank=True,
                db_column='usuario_id',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='eventos_bitacora',
                to='usuarios.usuario'),
        ),
        migrations.AlterModelTable(
            name='bitacoraevento',
            table='bitacora',
        ),
    ]
