# Generated by GitHub Copilot on 2026-04-12

from django.db import migrations


def _ensure_bitacora_table_exists(apps, schema_editor):
    """Recrea la tabla `bitacora` si fue eliminada manualmente.

    Problema que resuelve:
    - Si la tabla se borró en la BD, pero las migraciones 0001/0002 siguen marcadas como
      aplicadas en `django_migrations`, Django NO vuelve a ejecutar CreateModel/AlterModelTable.

    Estrategia:
    - Inspecciona tablas existentes.
    - Si falta `bitacora`, crea la tabla a partir del estado actual del modelo en migraciones.

    Nota:
    - No intenta restaurar datos (si se borró la tabla, esos registros ya no existen).
    """

    connection = schema_editor.connection
    existing_tables = {name.lower()
                       for name in connection.introspection.table_names()}

    if "bitacora" in existing_tables:
        return

    BitacoraEvento = apps.get_model("bitacora", "BitacoraEvento")
    schema_editor.create_model(BitacoraEvento)


class Migration(migrations.Migration):

    dependencies = [
        ("bitacora", "0002_alter_bitacoraevento_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            _ensure_bitacora_table_exists,
            reverse_code=migrations.RunPython.noop),
    ]
