# Generated by Django 5.2.6 on 2026-05-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_recreate_bitacora_table_if_missing'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraevento',
            name='empresa',
            field=models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_eventos', to='empresas.empresa'),
        ),
    ]
