export const registerStyles = {
  iconWrapper: {
    width: '90px',
    height: '90px',
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.15)',
    border: '3px solid #fbbf24',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 16px',
    boxShadow: '0 0 30px rgba(245,158,11,0.5)',
  },
  backButton: {
    background: 'transparent',
    border: '1.5px solid #e5e7eb',
    borderRadius: '12px',
    padding: '12px',
    fontSize: '13px',
    fontWeight: '500',
    color: '#6b7280',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    fontFamily: "'Poppins', sans-serif',",
    transition: 'all 0.2s',
  },
}